### ISSUE TITLE
感谢你的翱翔门户成绩脚本，不过最近翱翔门户登陆似乎更新，佬有意向接着维护一下吗

### ISSUE THREAD

**Issue by qllokirin** [cheanus/Automation#1]
今天发现在点击登录的瞬间密码会变成`__RSA__xxxxxxx`，然后抓一下会发现发往`
https://uis.nwpu.edu.cn/cas/mfa/detect`的请求里面的密码字段已经加密了，我看了一会儿发现秘钥在`
https://uis.nwpu.edu.cn/cas/jwt/publicKey`的请求里面有，试了试加密但是跟学校发出去的那个请求里的密文不太一样，不太懂了，佬有兴趣研究一下吗

**Comment by cheanus** [comment]
刚才简单看了下，情况和你描述的一样，这个问题我最近尝试修复下。
顺便一提，这是我第一次遇到有人提issue😂，我还以为这个项目没人关注呢。

**Comment by cheanus** [comment]
已经fix了，你看看有啥问题没

**Comment by cheanus** [comment]
RSA相同公钥加密出的密文可以不同，所以你加密出的密文才对不上

**Comment by qllokirin** [comment]
> 已经fix了，你看看有啥问题没

很好很好太好了，已经好了

**Comment by qllokirin** [comment]
> RSA相同公钥加密出的密文可以不同，所以你加密出的密文才对不上

原来如此，感谢指点
